library(shiny)
library(ggplot2)
library(dplyr)
library(xlsx)
library(modelr)  # provides ModelObject(), ModelObjectFit()
library(pangr)  # provides smooth.adaptive.loess() for expandix()

source('lib/BioscreenExperimentRefClass.R')
source('lib/DataIndexExpanders.R')
source('lib/expandix.R')
source('lib/models.R')